### ISSUE TITLE
Is Test A4.0 valid BMPN?

### ISSUE THREAD

**Issue by gcsm1th** [bpmn-miwg/bpmn-miwg-test-suite#431]
I am not certain that the A4.0 reference model is valid BPMN.    Section 10.3 BPMN 2.0.1

"NOTE: All Message Flows MUST connect two separate Pools. They MAY connect to the Pool boundary or to Flow Objects within the Pool boundary." 

 The 2 message flows in this model connect Tasks in "Pool" with tasks in "Lane 1", which is not in any Pool.  This appears to violate the BPMN standard.

**Comment by alexismeneses** [comment]
This is because the *“internal”* or *“main”* Pool is not required to have boundary. Still it remains a Pool.

“Lane 1” has to be considered in such an “*internal*” Pool.

As per BPMN 2.0.2 Section 9.3
« *a Process that represents the work performed from the point of view of the modeler or the modeler’s organization can be considered “internal” and is NOT REQUIRED to be surrounded by the boundary of the Pool, while the other Pools in the Diagram MUST have their boundary (see Figure 9.5).* »

BTW, the mentionned figure [Figure 9.5 - Main (Internal) Pool without boundaries] shows such Message Flows connecting elements that reside in the internal Pool.

Should the validity be questionned, it would rather be on semantics because BPMN 2.0.2 Section 9.4 also reads « *A Message Flow is used to show the flow of Messages between __two Participants__ that are prepared to send and receive them.* » But there's only one paticipant defined in the [collaboration](https://github.com/bpmn-miwg/bpmn-miwg-test-suite/blob/26a896349883a06f4cb4d35e1901c69d97e1a93d/Reference/A.4.0.bpmn#L95-99).

**Comment by dgagne** [comment]
Webmeeting 11 Mar 2015
o	Discussion regarding whether the process under focus (i.e. without a pool) should generate a Participant
o	A quick survey of tools vendor present: all of Trisotech, itp commerce, Sparx, W4 and SAP only generate one participant in this situation.

**Comment by dgagne** [comment]
Webmeeting 18 Mar 2015
o	The spec seems to be clear enough as all vendors had the same implementation
o	Issue to be closed no changes
